<div @if($article) wire:poll.30s="autosave" @endif>
    <span class="eyebrow">Ruang tulis</span>
    <h1 class="mt-1 font-display text-3xl font-bold">{{ $article ? 'Ubah berita' : 'Tulis berita baru' }}</h1>
    <form wire:submit="save" class="mt-7 grid gap-6 xl:grid-cols-[1fr_340px]">
        <div class="admin-card grid gap-5">
            <div><label class="label" for="title">Judul berita *</label><input id="title" wire:model="title" class="field"><p class="mt-1 text-xs text-muted">Alamat berita dibuat otomatis saat pertama kali disimpan.</p>@error('title')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div><label class="label" for="excerpt">Ringkasan *</label><textarea id="excerpt" wire:model="excerpt" rows="3" class="field"></textarea>@error('excerpt')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div><label class="label" for="article-body">Isi berita *</label><x-form.rich-text id="article-body" property="body" :value="$body" allow-images /><p class="mt-1 text-xs text-muted">Gunakan toolbar untuk mengatur teks. Gambar JPG, PNG, atau WebP maksimal 5 MB dapat disisipkan dari toolbar atau drag-and-drop.</p>@error('body')<p class="field-error">{{ $message }}</p>@enderror</div>
            <div class="grid gap-4 sm:grid-cols-2"><div><label class="label" for="image">Gambar utama</label><input id="image" wire:model="featuredImageUpload" type="file" accept="image/jpeg,image/png,image/webp" class="field file:mr-3 file:rounded-md file:border-0 file:bg-brand file:px-3 file:py-1 file:font-bold file:text-white"><p class="mt-1 text-xs text-muted">Gambar otomatis dioptimalkan ke WebP dan dibuatkan thumbnail bila server mendukung GD.</p>@error('featuredImageUpload')<p class="field-error">{{ $message }}</p>@enderror<div class="mt-3"><label class="label" for="media-picker">Atau pilih dari pustaka</label><div wire:ignore><select id="media-picker" wire:model.live="selectedMediaId" data-tom-select data-placeholder="Pilih media"><option value="">Pilih media</option>@foreach($mediaItems as $media)<option value="{{ $media->id }}">{{ $media->filename }}</option>@endforeach</select></div></div>@if($featuredImageUpload)<img src="{{ $featuredImageUpload->temporaryUrl() }}" alt="Pratinjau gambar baru" class="mt-3 aspect-video w-full rounded-lg object-cover">@elseif($featuredImage)<img src="{{ $featuredImage }}" alt="Gambar utama saat ini" class="mt-3 aspect-video w-full rounded-lg object-cover">@endif</div><div class="grid content-start gap-4"><div><label class="label" for="alt">Teks alternatif gambar</label><input id="alt" wire:model="imageAlt" class="field" placeholder="Jelaskan isi gambar untuk aksesibilitas"></div><div><label class="label" for="image-caption">Caption</label><input id="image-caption" wire:model="imageCaption" class="field"></div><div><label class="label" for="image-credit">Kredit foto</label><input id="image-credit" wire:model="imageCredit" class="field"></div></div></div>
            <div class="grid gap-4 sm:grid-cols-2"><div><label class="label" for="seo-title">Judul SEO</label><input id="seo-title" wire:model="seoTitle" class="field"></div><div><label class="label" for="seo-description">Deskripsi SEO</label><textarea id="seo-description" wire:model="seoDescription" rows="2" class="field"></textarea></div></div>
            <div><label class="label" for="note">Catatan perubahan</label><input id="note" wire:model="changeNote" class="field" placeholder="Jelaskan revisi penting"></div>
        </div>
        <aside class="grid content-start gap-5">
            <div class="admin-card grid gap-4">
                <h2 class="font-bold">Publikasi</h2>
                <div><label class="label" for="status">Status</label><div wire:ignore><select id="status" wire:model.live="status" data-tom-select data-placeholder="Pilih status">@foreach($statuses as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></div></div>
                <div><label class="label" for="content-type">Jenis konten</label><div wire:ignore><select id="content-type" wire:model="contentType" data-tom-select><option value="article">Artikel</option><option value="photo">Berita foto</option><option value="video">Berita video</option></select></div></div>
                <div><label class="label" for="carousel-order">Urutan carousel</label><input id="carousel-order" type="number" min="0" max="999" wire:model="carouselOrder" class="field"></div>
                @if($status === 'scheduled')<div><label class="label" for="scheduled">Waktu terbit</label><input id="scheduled" type="datetime-local" wire:model="scheduledAt" class="field">@error('scheduledAt')<p class="field-error">{{ $message }}</p>@enderror</div>@endif
                <div><label class="label" for="category">Kanal *</label><div wire:ignore><select id="category" wire:model="categoryId" data-tom-select data-placeholder="Pilih kanal"><option value="">Pilih kanal</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>@error('categoryId')<p class="field-error">{{ $message }}</p>@enderror</div>
                <div><label class="label" for="tags">Tag</label><div wire:ignore><select id="tags" multiple data-tom-select data-placeholder="Cari dan pilih tag" data-livewire-property="tagIds">@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected(in_array((string) $tag->id, $tagIds, true))>{{ $tag->name }}</option>@endforeach</select></div>@error('tagIds.*')<p class="field-error">{{ $message }}</p>@enderror</div>
                <button class="btn-primary w-full" wire:loading.attr="disabled"><span wire:loading.remove>Simpan berita</span><span wire:loading>Menyimpan...</span></button>@if($article)<a class="btn-secondary w-full" href="{{ route('admin.articles.preview', $article) }}" target="_blank">Pratinjau berita</a><p class="text-center text-xs text-muted">@if($lastAutosavedAt)Tersimpan otomatis pukul {{ $lastAutosavedAt }}@elsePerubahan draft disimpan otomatis setiap 30 detik.@endif</p>@endif
            </div>
            <div class="admin-card grid gap-3"><h2 class="font-bold">Penempatan</h2>@foreach([['isHeadline', 'Headline utama'], ['isFeatured', 'Berita pilihan'], ['isBreaking', 'Radar Terkini'], ['allowComments', 'Izinkan komentar']] as [$model, $label])<label class="flex min-h-11 items-center gap-3"><input type="checkbox" wire:model="{{ $model }}"> {{ $label }}</label>@endforeach</div>
            @if($article)<div class="admin-card"><h2 class="font-bold">Riwayat editorial</h2><div class="mt-3 grid max-h-72 gap-3 overflow-y-auto">@forelse($statusHistories as $history)<div class="border-l-2 border-brand pl-3 text-sm"><strong>{{ str($history->to_status)->headline() }}</strong><p class="text-xs text-muted">{{ $history->actor->name }} · {{ $history->created_at->diffForHumans() }}</p></div>@empty<p class="text-sm text-muted">Belum ada perubahan status.</p>@endforelse</div>@if($revisions->isNotEmpty())<h3 class="mt-5 font-bold">Revisi konten</h3><div class="mt-2 grid gap-2">@foreach($revisions as $revision)<button type="button" wire:click="loadRevision({{ $revision->id }})" class="rounded-lg border border-line p-2 text-left text-xs hover:border-brand"><strong class="block">{{ $revision->created_at->format('d/m/Y H:i') }}</strong>{{ $revision->change_note ?: 'Tanpa catatan' }}</button>@endforeach</div>@endif</div>@endif
        </aside>
    </form>
</div>
