<div>
    <div class="flex flex-wrap items-end justify-between gap-4"><div><span class="eyebrow">Aset visual</span><h1 class="mt-1 font-display text-3xl font-bold">Pustaka media</h1></div><button wire:click="create" class="btn-primary"><i class="fa-solid fa-cloud-arrow-up"></i> Tambah media</button></div>
    @if(session('success'))<p class="mt-4 rounded-lg bg-green-100 p-3 text-green-900 dark:bg-green-950 dark:text-green-200">{{ session('success') }}</p>@endif
    <div class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">@forelse($mediaItems as $media)<article wire:key="media-{{ $media->id }}" class="admin-card"><img src="{{ Storage::disk($media->disk)->url($media->thumbnail_path ?: $media->path) }}" alt="{{ $media->alt_text }}" class="aspect-video w-full rounded-lg object-cover" loading="lazy" width="640"><p class="mt-3 truncate font-bold">{{ $media->filename }}</p><p class="text-xs text-muted">{{ number_format($media->size/1024) }} KB · {{ $media->uploader->name }}</p><div class="mt-3 flex gap-2"><button wire:click="edit({{ $media->id }})" class="btn-secondary">Edit</button>@if(auth()->user()->hasPermission('media.manage'))<button wire:click="delete({{ $media->id }})" wire:confirm="Hapus media ini?" class="btn-danger">Hapus</button>@endif</div></article>@empty<p class="admin-card col-span-full text-center text-muted">Belum ada media.</p>@endforelse</div><div class="mt-6">{{ $mediaItems->links() }}</div>
    @if($showModal)<div class="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/65 p-4" role="dialog" aria-modal="true" aria-labelledby="media-modal-title" wire:keydown.escape.window="closeModal"><button type="button" wire:click="closeModal" class="absolute inset-0 cursor-default" aria-label="Tutup modal"></button><form wire:submit="saveMedia" class="admin-card relative z-10 w-full max-w-xl shadow-2xl"><div class="flex items-center justify-between gap-4"><h2 id="media-modal-title" class="font-display text-2xl font-bold">{{ $editingId ? 'Edit metadata media' : 'Tambah media' }}</h2><button type="button" wire:click="closeModal" class="icon-button" aria-label="Tutup"><i class="fa-solid fa-xmark"></i></button></div><div class="mt-5 grid gap-4">
        @unless($editingId)<div><label class="label" for="media-file">Gambar JPG, PNG, atau WebP *</label><input id="media-file" type="file" wire:model="file" accept="image/jpeg,image/png,image/webp" class="field">@error('file')<p class="field-error">{{ $message }}</p>@enderror<div wire:loading wire:target="file" class="mt-2 text-sm text-muted">Memproses gambar...</div>@if($file)<img src="{{ $file->temporaryUrl() }}" alt="Pratinjau gambar" class="mt-3 aspect-video w-full rounded-lg bg-muted object-cover">@endif<p class="mt-2 text-xs text-muted">Ukuran maksimal 5 MB.</p></div>@endunless
        <div><label class="label" for="media-alt">Teks alternatif</label><input id="media-alt" wire:model="altText" class="field" placeholder="Otomatis dibuat dari nama file jika dikosongkan">@error('altText')<p class="field-error">{{ $message }}</p>@enderror</div><div><label class="label" for="media-caption">Caption</label><textarea id="media-caption" wire:model="caption" rows="3" class="field"></textarea></div><div><label class="label" for="media-credit">Kredit foto</label><input id="media-credit" wire:model="credit" class="field"></div>
    </div><div class="mt-6 flex justify-end gap-2"><button type="button" wire:click="closeModal" class="btn-secondary">Batal</button><button class="btn-primary" wire:loading.attr="disabled" wire:target="saveMedia"><span wire:loading.remove wire:target="saveMedia">{{ $editingId ? 'Simpan perubahan' : 'Unggah gambar' }}</span><span wire:loading wire:target="saveMedia">Menyimpan...</span></button></div></form></div>@endif
</div>
