<div>
    <span class="eyebrow">Navigasi portal</span><h1 class="mt-1 font-display text-3xl font-bold">Menu</h1>
    @if(session('success'))<p class="mt-4 rounded-lg bg-green-100 p-3 text-green-900">{{ session('success') }}</p>@endif
    <div class="mt-6 grid gap-6 xl:grid-cols-[320px_1fr]">
        <aside class="admin-card"><div class="flex items-center justify-between gap-3"><h2 class="font-bold">Daftar menu</h2><button wire:click="resetMenu" class="btn-secondary">Baru</button></div><div class="mt-4 grid gap-2">@forelse($menus as $menu)<button wire:key="menu-{{ $menu->id }}" wire:click="selectMenu({{ $menu->id }})" class="flex min-h-12 items-center justify-between rounded-lg border border-line px-3 text-left {{ $menuId === $menu->id ? 'ring-2 ring-brand' : '' }}"><span><strong>{{ $menu->name }}</strong><small class="block text-muted">{{ $menu->location }}</small></span><span class="status-pill">{{ $menu->items_count }}</span></button>@empty<p class="text-sm text-muted">Belum ada menu.</p>@endforelse</div></aside>
        <div class="grid gap-6"><form wire:submit="saveMenu" class="admin-card grid gap-4"><h2 class="font-bold">{{ $menuId ? 'Pengaturan menu' : 'Buat menu' }}</h2><div class="grid gap-4 md:grid-cols-2"><div><label class="label" for="menu-name">Nama</label><input id="menu-name" wire:model="name" class="field">@error('name')<p class="field-error">{{ $message }}</p>@enderror</div><div><label class="label" for="menu-location">Lokasi</label><div wire:ignore><select id="menu-location" wire:model="location" data-tom-select data-livewire-property="location"><option value="header">Header</option><option value="footer">Footer</option></select></div>@error('location')<p class="field-error">{{ $message }}</p>@enderror</div></div><label class="flex min-h-11 items-center gap-2"><input type="checkbox" wire:model="menuActive"> Menu aktif</label><div class="flex gap-2"><button class="btn-primary">Simpan menu</button>@if($menuId)<button type="button" wire:click="deleteMenu" wire:confirm="Hapus menu beserta seluruh itemnya?" class="btn-danger">Hapus menu</button>@endif</div></form>
            @if($menuId)<div class="grid gap-6 lg:grid-cols-[340px_1fr]"><form wire:submit="saveItem" class="admin-card grid content-start gap-4"><h2 class="font-bold">{{ $itemId ? 'Edit item' : 'Tambah item' }}</h2><div><label class="label" for="item-label">Label</label><input id="item-label" wire:model="label" class="field"></div><div><label class="label" for="item-url">URL atau path</label><input id="item-url" wire:model="url" class="field" placeholder="/terbaru atau https://..."></div><div><label class="label" for="item-parent">Item induk (opsional)</label><div wire:ignore><select id="item-parent" wire:model="parentId" data-tom-select data-livewire-property="parentId" data-placeholder="Pilih item induk"><option value="">Tanpa induk</option>@foreach($items->whereNull('parent_id') as $parentItem)@if($parentItem->id !== $itemId)<option value="{{ $parentItem->id }}">{{ $parentItem->label }}</option>@endif @endforeach</select></div>@error('parentId')<p class="field-error">{{ $message }}</p>@enderror</div><div><label class="label" for="item-target">Target</label><div wire:ignore><select id="item-target" wire:model="target" data-tom-select data-livewire-property="target"><option value="_self">Tab yang sama</option><option value="_blank">Tab baru</option></select></div></div><div><label class="label" for="item-order">Urutan</label><input id="item-order" type="number" min="0" wire:model="order" class="field"></div><label class="flex min-h-11 items-center gap-2"><input type="checkbox" wire:model="itemActive"> Item aktif</label><div class="flex gap-2"><button class="btn-primary">Simpan item</button>@if($itemId)<button type="button" wire:click="resetItem" class="btn-secondary">Batal</button>@endif</div></form><div class="admin-card overflow-x-auto"><table class="data-table"><thead><tr><th>Item</th><th>Urutan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($items as $item)<tr wire:key="menu-item-{{ $item->id }}"><td><strong>{{ $item->parent ? '↳ ' : '' }}{{ $item->label }}</strong><small class="block max-w-xs truncate text-muted">@if($item->parent)Induk: {{ $item->parent->label }} · @endif{{ $item->url }}</small></td><td>{{ $item->order }}</td><td>{{ $item->is_active ? 'Aktif' : 'Nonaktif' }}</td><td><div class="flex gap-2"><button wire:click="editItem({{ $item->id }})" class="btn-secondary">Edit</button><button wire:click="deleteItem({{ $item->id }})" wire:confirm="Hapus item menu?" class="btn-danger">Hapus</button></div></td></tr>@empty<tr><td colspan="4" class="text-center text-muted">Belum ada item.</td></tr>@endforelse</tbody></table></div></div>@endif
        </div>
    </div>
</div>
