<div>
    <div class="flex flex-wrap items-end justify-between gap-4"><div><span class="eyebrow">Struktur konten</span><h1 class="mt-1 font-display text-3xl font-bold">Kanal dan tag</h1></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.taxonomy.tags.create') }}" wire:navigate class="btn-secondary"><i class="fa-solid fa-tag"></i> Tambah tag</a><a href="{{ route('admin.taxonomy.categories.create') }}" wire:navigate class="btn-primary"><i class="fa-solid fa-plus"></i> Tambah kanal</a></div></div>
    @if(session('success'))<p class="mt-4 rounded-lg bg-green-100 p-3 text-green-900">{{ session('success') }}</p>@endif
    @error('category')<p class="mt-4 rounded-lg bg-red-100 p-3 text-red-900">{{ $message }}</p>@enderror
    <div class="mt-6 grid gap-6 xl:grid-cols-2">
        <section class="admin-card"><h2 class="text-xl font-bold">Kanal berita</h2><div class="mt-5 divide-y divide-line">@forelse($categories as $category)<div wire:key="category-{{ $category->id }}" class="flex min-h-16 items-center gap-3"><div><strong>{{ $category->name }}</strong><p class="text-xs text-muted">@if($category->parent)Induk: {{ $category->parent->name }} · @endif{{ $category->articles_count }} berita · {{ $category->is_active ? 'Aktif' : 'Nonaktif' }}</p></div><a href="{{ route('admin.taxonomy.categories.edit', $category) }}" wire:navigate class="icon-button ml-auto" aria-label="Edit kanal"><i class="fa-solid fa-pen"></i></a><button wire:click="deleteCategory({{ $category->id }})" wire:confirm="Hapus kanal ini?" class="icon-button text-red-600" aria-label="Hapus kanal"><i class="fa-solid fa-trash"></i></button></div>@empty<p class="py-8 text-center text-muted">Belum ada kanal.</p>@endforelse</div></section>
        <section class="admin-card"><h2 class="text-xl font-bold">Tag</h2><div class="mt-5 flex flex-wrap gap-2">@forelse($tags as $tag)<span wire:key="tag-{{ $tag->id }}" class="inline-flex items-center gap-1 rounded-full bg-muted py-1 pl-3 pr-1 text-sm">{{ $tag->name }} ({{ $tag->articles_count }}) <a href="{{ route('admin.taxonomy.tags.edit', $tag) }}" wire:navigate class="icon-button size-8" aria-label="Edit tag"><i class="fa-solid fa-pen"></i></a><button wire:click="deleteTag({{ $tag->id }})" wire:confirm="Hapus tag ini?" class="icon-button size-8 text-red-600" aria-label="Hapus tag"><i class="fa-solid fa-xmark"></i></button></span>@empty<p class="py-8 text-center text-muted">Belum ada tag.</p>@endforelse</div></section>
    </div>
</div>
